export const categoriesDinner = [
  {
    id: "01",
    name: "Fajitas de Pollo",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-01.webp"),
    rating: "4.7",
    ingredients: [
      "Pechuga de Pollo",
      "Pimientos",
      "Cebolla",
      "Tortillas",
      "Especias",
    ],
    time: "30",
    difficulty: "Medio",
    calories: "400",
    color: "bg-yellow-200",
    description:
      "Fajitas de pollo marinadas y asadas, servidas con pimientos, cebolla y tortillas.",
    steps: [
      "Paso 1: Marinar el pollo con especias.",
      "Paso 2: Asar el pollo, los pimientos y la cebolla.",
      "Paso 3: Servir con tortillas.",
    ],
  },
  {
    id: "02",
    name: "Sopa de Tortilla",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-02.webp"),
    rating: "4.8",
    ingredients: [
      "Tortillas",
      "Tomates",
      "Aguacate",
      "Queso",
      "Caldo de Pollo",
    ],
    time: "35",
    difficulty: "Medio",
    calories: "300",
    color: "bg-orange-200",
    description:
      "Sopa de caldo de pollo con tiras de tortilla, tomate, aguacate y queso.",
    steps: [
      "Paso 1: Freír las tiras de tortilla.",
      "Paso 2: Cocinar el caldo con tomates.",
      "Paso 3: Servir el caldo con las tiras de tortilla, aguacate y queso.",
    ],
  },
  {
    id: "03",
    name: "Tacos de Pescado",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-03.webp"),
    rating: "4.9",
    ingredients: ["Filetes de Pescado", "Tortillas", "Col", "Lima", "Salsa"],
    time: "20",
    difficulty: "Fácil",
    calories: "350",
    color: "bg-blue-200",
    description: "Tacos de pescado fritos, servidos con col, lima y salsa.",
    steps: [
      "Paso 1: Marinar y freír los filetes de pescado.",
      "Paso 2: Calentar las tortillas.",
      "Paso 3: Servir el pescado en las tortillas con col, lima y salsa.",
    ],
  },
  {
    id: "04",
    name: "Tostadas de Pollo",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-04.webp"),
    rating: "4.7",
    ingredients: ["Tostadas", "Pollo", "Lechuga", "Frijoles", "Queso"],
    time: "25",
    difficulty: "Fácil",
    calories: "300",
    color: "bg-green-200",
    description:
      "Tostadas crujientes con pollo desmenuzado, lechuga, frijoles y queso.",
    steps: [
      "Paso 1: Cocinar y desmenuzar el pollo.",
      "Paso 2: Calentar las tostadas.",
      "Paso 3: Servir el pollo en las tostadas con lechuga, frijoles y queso.",
    ],
  },
  {
    id: "05",
    name: "Ensalada César",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-05.webp"),
    rating: "4.5",
    ingredients: [
      "Lechuga Romana",
      "Pollo",
      "Crutones",
      "Queso Parmesano",
      "Aderezo César",
    ],
    time: "15",
    difficulty: "Fácil",
    calories: "250",
    color: "bg-yellow-300",
    description:
      "Ensalada de lechuga romana con pollo a la parrilla, crutones, queso parmesano y aderezo César.",
    steps: [
      "Paso 1: Asar el pollo.",
      "Paso 2: Mezclar la lechuga con crutones y queso.",
      "Paso 3: Añadir el pollo y aderezo César.",
    ],
  },
  {
    id: "06",
    name: "Tamales de Rajas",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-06.webp"),
    rating: "4.6",
    ingredients: [
      "Masa de Maíz",
      "Rajas de Chile Poblano",
      "Queso",
      "Hojas de Maíz",
    ],
    time: "30",
    difficulty: "Medio",
    calories: "400",
    color: "bg-green-300",
    description:
      "Tamales rellenos de rajas de chile poblano y queso, envueltos en hojas de maíz.",
    steps: [
      "Paso 1: Preparar la masa de maíz.",
      "Paso 2: Rellenar con rajas y queso.",
      "Paso 3: Envolver en hojas de maíz y cocer al vapor.",
    ],
  },
  {
    id: "07",
    name: "Sopes de Carne Asada",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-07.webp"),
    rating: "4.8",
    ingredients: [
      "Masa de Maíz",
      "Carne Asada",
      "Frijoles Refritos",
      "Queso",
      "Lechuga",
    ],
    time: "30",
    difficulty: "Medio",
    calories: "450",
    color: "bg-brown-300",
    description:
      "Sopes de masa de maíz fritos, cubiertos con carne asada, frijoles, queso y lechuga.",
    steps: [
      "Paso 1: Preparar y freír la masa de maíz.",
      "Paso 2: Asar la carne.",
      "Paso 3: Servir los sopes con frijoles, carne, queso y lechuga.",
    ],
  },
  {
    id: "08",
    name: "Burritos de Frijoles",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-08.webp"),
    rating: "4.7",
    ingredients: [
      "Tortillas de Harina",
      "Frijoles Refritos",
      "Arroz",
      "Queso",
      "Salsa",
    ],
    time: "20",
    difficulty: "Fácil",
    calories: "400",
    color: "bg-orange-300",
    description:
      "Tortillas de harina rellenas de frijoles refritos, arroz, queso y salsa.",
    steps: [
      "Paso 1: Calentar las tortillas.",
      "Paso 2: Rellenar con frijoles, arroz, queso y salsa.",
      "Paso 3: Enrollar y servir.",
    ],
  },
  {
    id: "09",
    name: "Gorditas de Chicharrón",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-09.webp"),
    rating: "4.9",
    ingredients: [
      "Masa de Maíz",
      "Chicharrón",
      "Frijoles Refritos",
      "Queso",
      "Lechuga",
    ],
    time: "25",
    difficulty: "Medio",
    calories: "500",
    color: "bg-red-500",
    description:
      "Gorditas rellenas de chicharrón, frijoles refritos, queso y lechuga.",
    steps: [
      "Paso 1: Preparar y freír la masa de maíz.",
      "Paso 2: Rellenar con chicharrón, frijoles y queso.",
      "Paso 3: Servir con lechuga.",
    ],
  },
  {
    id: "10",
    name: "Chalupas",
    category: "Dinner",
    Image: require("../../assets/imgs/cenas/receta-10.webp"),
    rating: "4.6",
    ingredients: [
      "Tortillas",
      "Carne Deshebrada",
      "Salsa Roja",
      "Queso",
      "Cebolla",
    ],
    time: "30",
    difficulty: "Medio",
    calories: "350",
    color: "bg-red-600",
    description:
      "Tortillas fritas cubiertas con carne deshebrada, salsa roja, queso y cebolla.",
    steps: [
      "Paso 1: Freír las tortillas.",
      "Paso 2: Rellenar con carne deshebrada y salsa roja.",
      "Paso 3: Servir con queso y cebolla.",
    ],
  },
];
