export const categoriesLunch = [
  {
    id: "01",
    name: "Tacos al Pastor",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-01.webp"),
    rating: "4.9",
    ingredients: ["Carne de Cerdo", "Piña", "Cilantro", "Cebolla", "Tortillas"],
    time: "40",
    difficulty: "Medio",
    calories: "450",
    color: "bg-green-200",
    description:
      "Tacos de carne de cerdo marinada y asada, servidos con piña, cilantro y cebolla.",
    steps: [
      "Paso 1: Marinar la carne de cerdo con achiote y especias.",
      "Paso 2: Asar la carne y la piña.",
      "Paso 3: Servir en tortillas con cilantro y cebolla.",
    ],
  },
  {
    id: "02",
    name: "Enchiladas Verdes",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-02.webp"),
    rating: "4.7",
    ingredients: ["Tortillas", "Salsa Verde", "Pollo", "Queso", "Crema"],
    time: "35",
    difficulty: "Medio",
    calories: "400",
    color: "bg-green-300",
    description:
      "Tortillas rellenas de pollo y cubiertas con salsa verde, queso y crema.",
    steps: [
      "Paso 1: Cocinar el pollo y desmenuzarlo.",
      "Paso 2: Rellenar las tortillas con el pollo.",
      "Paso 3: Cubrir con salsa verde, queso y crema.",
    ],
  },
  {
    id: "03",
    name: "Guacamole",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-03.webp"),
    rating: "4.8",
    ingredients: ["Aguacates", "Cebolla", "Tomate", "Cilantro", "Limón", "Sal"],
    time: "10",
    difficulty: "Fácil",
    calories: "150",
    color: "bg-green-100",
    description: "Crema de aguacate con trozos de cebolla, tomate y cilantro.",
    steps: [
      "Paso 1: Triturar los aguacates.",
      "Paso 2: Mezclar con la cebolla, tomate y cilantro picados.",
      "Paso 3: Añadir jugo de limón y sal al gusto.",
    ],
  },
  {
    id: "04",
    name: "Chiles en Nogada",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-04.webp"),
    rating: "4.9",
    ingredients: ["Chiles Poblanos", "Picadillo", "Nuez", "Crema", "Granada"],
    time: "90",
    difficulty: "High",
    calories: "600",
    color: "bg-green-400",
    description:
      "Chiles rellenos de picadillo cubiertos con una salsa de nuez y decorados con granada.",
    steps: [
      "Paso 1: Asar y pelar los chiles poblanos.",
      "Paso 2: Rellenar con picadillo.",
      "Paso 3: Cubrir con salsa de nuez y decorar con granada.",
    ],
  },
  {
    id: "05",
    name: "Ceviche de Pescado",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-05.webp"),
    rating: "4.7",
    ingredients: ["Pescado", "Limón", "Cebolla", "Tomate", "Cilantro", "Chile"],
    time: "20",
    difficulty: "Fácil",
    calories: "200",
    color: "bg-green-100",
    description: "Pescado marinado en jugo de limón con vegetales frescos.",
    steps: [
      "Paso 1: Marinar el pescado en jugo de limón.",
      "Paso 2: Mezclar con cebolla, tomate, cilantro y chile picados.",
    ],
  },
  {
    id: "06",
    name: "Mole Poblano",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-06.webp"),
    rating: "4.8",
    ingredients: ["Pollo", "Mole", "Arroz", "Tortillas"],
    time: "12n",
    difficulty: "High",
    calories: "500",
    color: "bg-green-400",
    description:
      "Pollo cubierto con mole poblano acompañado de arroz y tortillas.",
    steps: [
      "Paso 1: Cocinar el pollo.",
      "Paso 2: Preparar el mole.",
      "Paso 3: Servir el pollo con mole, arroz y tortillas.",
    ],
  },
  {
    id: "07",
    name: "Quesadillas",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-07.webp"),
    rating: "4.6",
    ingredients: ["Tortillas", "Queso", "Champiñones", "Espinacas"],
    time: "15",
    difficulty: "Fácil",
    calories: "300",
    color: "bg-green-200",
    description:
      "Tortillas rellenas de queso derretido y otros ingredientes opcionales.",
    steps: [
      "Paso 1: Rellenar las tortillas con queso y otros ingredientes.",
      "Paso 2: Cocinar en la plancha hasta que el queso se derrita.",
    ],
  },
  {
    id: "08",
    name: "Pozole Rojo",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-08.webp"),
    rating: "4.9",
    ingredients: [
      "Maíz Pozolero",
      "Pollo o Cerdo",
      "Chile Guajillo",
      "Rábanos",
      "Lechuga",
      "Limón",
    ],
    time: "15n",
    difficulty: "Medio",
    calories: "350",
    color: "bg-green-300",
    description:
      "Sopa tradicional mexicana con maíz y carne en caldo de chile.",
    steps: [
      "Paso 1: Cocer el maíz y la carne.",
      "Paso 2: Preparar el caldo con chile.",
      "Paso 3: Servir con rábanos, lechuga y limón.",
    ],
  },
  {
    id: "09",
    name: "Chilaquiles",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-09.webp"),
    rating: "4.7",
    ingredients: [
      "Tortillas",
      "Salsa Roja o Verde",
      "Queso",
      "Crema",
      "Pollo (opcional)",
    ],
    time: "30",
    difficulty: "Fácil",
    calories: "400",
    color: "bg-green-200",
    description:
      "Tortillas fritas bañadas en salsa y cubiertas con queso y crema.",
    steps: [
      "Paso 1: Freír las tortillas.",
      "Paso 2: Bañar en salsa.",
      "Paso 3: Cubrir con queso, crema y pollo si se desea.",
    ],
  },
  {
    id: "10",
    name: "Sopes",
    category: "Lunch",
    Image: require("../../assets/imgs/comidas/receta-10.webp"),
    rating: "4.8",
    ingredients: ["Masa", "Frijoles", "Queso", "Crema", "Lechuga", "Salsa"],
    time: "40",
    difficulty: "Medio",
    calories: "350",
    color: "bg-green-300",
    description: "Base de masa frita con frijoles y otros ingredientes encima.",
    steps: [
      "Paso 1: Formar las bases con la masa.",
      "Paso 2: Freír las bases.",
      "Paso 3: Añadir frijoles, queso, crema, lechuga y salsa encima.",
    ],
  },
];
