export const categoriesSnacks = [
  {
    id: "01",
    name: "Tortilla Española",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-01.webp"),
    rating: "4.5",
    ingredients: ["Huevos", "Papas", "Cebolla", "Aceite de Oliva"],
    time: "30",
    difficulty: "Fácil",
    calories: "300",
    color: "bg-yellow-200",
    description:
      "La tortilla española es un plato clásico de España hecho con huevos, papas y cebolla, cocinado lentamente en aceite de oliva hasta obtener una textura dorada y jugosa.",
    steps: [
      "Paso 1: Pelar y cortar las papas y cebolla.",
      "Paso 2: Freír las papas y la cebolla en aceite de oliva.",
      "Paso 3: Batir los huevos y mezclarlos con las papas y cebolla.",
      "Paso 4: Cocinar la mezcla en una sartén hasta que la tortilla esté dorada y cuajada.",
    ],
  },
  {
    id: "02",
    name: "Pizza Margherita",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-02.webp"),
    rating: "4.8",
    ingredients: [
      "Masa de Pizza",
      "Tomate",
      "Mozzarella",
      "Albahaca",
      "Aceite de Oliva",
    ],
    time: "20",
    difficulty: "Medio",
    calories: "400",
    color: "bg-red-200",
    description:
      "La Pizza Margherita es una pizza tradicional italiana hecha con una base de masa, salsa de tomate, mozzarella fresca y hojas de albahaca, cocinada hasta que el queso esté burbujeante y dorado.",
    steps: [
      "Paso 1: Extender la masa de pizza sobre una superficie enharinada.",
      "Paso 2: Untar la salsa de tomate sobre la masa.",
      "Paso 3: Añadir la mozzarella y las hojas de albahaca.",
      "Paso 4: Hornear hasta que la masa esté crujiente y el queso derretido.",
    ],
  },

  {
    id: "03",
    name: "Sushi",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-03.webp"),
    rating: "4.8",
    ingredients: ["Arroz", "Alga Nori", "Pescado Crudo", "Salsa de Soja"],
    time: "45",
    difficulty: "Medio",
    calories: "300",
    color: "bg-green-200",
    description:
      "El sushi es un plato japonés que consiste en arroz aderezado con vinagre acompañado de varios ingredientes, como mariscos, vegetales y, a menudo, pescado crudo.",
    steps: [
      "Paso 1: Cocer el arroz y mezclar con vinagre.",
      "Paso 2: Colocar el arroz sobre el alga nori y añadir el pescado.",
      "Paso 3: Enrollar y cortar el sushi.",
      "Paso 4: Servir con salsa de soja.",
    ],
  },
  {
    id: "04",
    name: "Paella",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-04.webp"),
    rating: "4.7",
    ingredients: ["Arroz", "Mariscos", "Pollo", "Azafrán", "Vegetales"],
    time: "60",
    difficulty: "Hard",
    calories: "500",
    color: "bg-yellow-200",
    description:
      "La paella es un plato español de arroz que se cocina tradicionalmente en una sartén ancha y poco profunda, con ingredientes como mariscos, pollo, vegetales y especias.",
    description: [
      "Paso 1: Sofreír los vegetales y el pollo.",
      "Paso 2: Añadir el arroz y el caldo con azafrán.",
      "Paso 3: Incorporar los mariscos.",
      "Paso 4: Cocinar hasta que el arroz esté hecho.",
    ],
  },
  {
    id: "05",
    name: "Pad Thai",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-05.webp"),
    rating: "4.6",
    ingredients: [
      "Fideos de Arroz",
      "Pollo",
      "Huevos",
      "Salsa de Tamarindo",
      "Maní",
    ],
    time: "30",
    difficulty: "Medio",
    calories: "400",
    color: "bg-orange-200",
    description:
      "El Pad Thai es un plato tailandés que consiste en fideos de arroz salteados con pollo, camarones, huevos, y una mezcla de salsa de tamarindo, salsa de pescado, azúcar de palma y maní tostado.",
    description: [
      "Paso 1: Cocer los fideos de arroz.",
      "Paso 2: Saltear el pollo y los huevos.",
      "Paso 3: Añadir los fideos y la salsa de tamarindo.",
      "Paso 4: Mezclar todo y servir con maní.",
    ],
  },
  {
    id: "06",
    name: "Fish and Chips",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-06.webp"),
    rating: "4.4",
    ingredients: ["Pescado", "Papas", "Harina", "Aceite"],
    time: "25",
    difficulty: "Fácil",
    calories: "600",
    color: "bg-blue-200",
    description:
      "Fish and Chips es un plato británico que consiste en filetes de pescado rebozados y fritos, acompañados de papas fritas.",
    steps: [
      "Paso 1: Rebozar los filetes de pescado en harina.",
      "Paso 2: Freír el pescado y las papas en aceite caliente.",
      "Paso 3: Escurrir y servir.",
    ],
  },
  {
    id: "07",
    name: "Spaghetti Carbonara",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-07.webp"),
    rating: "4.5",
    ingredients: ["Spaghetti", "Huevos", "Queso Pecorino", "Panceta"],
    time: "20",
    difficulty: "Medio",
    calories: "450",
    color: "bg-pink-200",
    description:
      "La Carbonara es un plato de pasta italiano que se prepara con huevos, queso pecorino y panceta, creando una salsa cremosa y deliciosa.",
    steps: [
      "Paso 1: Cocer la pasta.",
      "Paso 2: Saltear la panceta.",
      "Paso 3: Mezclar los huevos con el queso pecorino.",
      "Paso 4: Combinar todo y servir.",
    ],
  },
  {
    id: "08",
    name: "Curry de Pollo",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-08.webp"),
    rating: "4.3",
    ingredients: ["Pollo", "Curry", "Leche de Coco", "Vegetales"],
    time: "35",
    difficulty: "Medio",
    calories: "500",
    color: "bg-red-200",
    description:
      "El curry de pollo es un plato popular en muchas cocinas asiáticas, cocinado con una mezcla de especias y leche de coco para un sabor rico y cremoso.",
    steps: [
      "Paso 1: Cocinar el pollo con las especias de curry.",
      "Paso 2: Añadir los vegetales y la leche de coco.",
      "Paso 3: Cocinar a fuego lento hasta que los sabores se mezclen.",
    ],
  },
  {
    id: "09",
    name: "Falafel",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-09.webp"),
    rating: "4.6",
    ingredients: ["Garbanzos", "Cebolla", "Ajo", "Especias"],
    time: "25",
    difficulty: "Fácil",
    calories: "300",
    color: "bg-green-200",
    description:
      "El falafel es un plato del Medio Oriente hecho de garbanzos molidos mezclados con cebolla, ajo y especias, formado en bolas o croquetas y frito.",
    steps: [
      "Paso 1: Mezclar los garbanzos con cebolla, ajo y especias.",
      "Paso 2: Formar bolas o croquetas.",
      "Paso 3: Freír hasta que estén dorados.",
    ],
  },
  {
    id: "10",
    name: "Hamburguesa",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-10.webp"),
    rating: "4.7",
    ingredients: ["Carne de Res", "Pan", "Lechuga", "Tomate", "Queso"],
    time: "20",
    difficulty: "Fácil",
    calories: "550",
    color: "bg-brown-200",
    description:
      "La hamburguesa es un clásico de la comida rápida, consistiendo en una carne de res molida cocinada y servida en un pan con una variedad de ingredientes como lechuga, tomate y queso.",
    steps: [
      "Paso 1: Formar y cocinar las hamburguesas de carne.",
      "Paso 2: Preparar los panes con los ingredientes.",
      "Paso 3: Servir la hamburguesa con los acompañamientos.",
    ],
  },
  {
    id: "11",
    name: "Ratatouille",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-11.webp"),
    rating: "4.5",
    ingredients: ["Berenjena", "Calabacín", "Pimiento", "Tomate", "Ajo"],
    time: "40",
    difficulty: "Medio",
    calories: "200",
    color: "bg-yellow-200",
    description:
      "El Ratatouille es un plato tradicional francés que consiste en vegetales cocidos lentamente en aceite de oliva, típicamente berenjena, calabacín, pimiento y tomate.",
    steps: [
      "Paso 1: Cortar los vegetales en rodajas.",
      "Paso 2: Cocinar a fuego lento con ajo y aceite de oliva.",
      "Paso 3: Servir caliente.",
    ],
  },
  {
    id: "12",
    name: "Shakshuka",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-12.webp"),
    rating: "4.3",
    ingredients: ["Tomates", "Pimientos", "Huevos", "Cebolla", "Especias"],
    time: "30",
    difficulty: "Medio",
    calories: "350",
    color: "bg-red-200",
    description:
      "La Shakshuka es un plato de Oriente Medio y África del Norte que consiste en huevos escalfados en una salsa de tomate picante con pimientos y cebolla.",
    steps: [
      "Paso 1: Cocinar tomates, pimientos y cebolla con especias.",
      "Paso 2: Romper los huevos sobre la salsa.",
      "Paso 3: Tapar y cocinar hasta que los huevos estén listos.",
    ],
  },
  {
    id: "13",
    name: "Pho",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-13.webp"),
    rating: "4.7",
    ingredients: ["Fideos de Arroz", "Carne de Res", "Caldo", "Hierbas"],
    time: "45",
    difficulty: "Hard",
    calories: "400",
    color: "bg-blue-200",
    descrption:
      "El Pho es una sopa vietnamita de fideos de arroz con carne de res y hierbas frescas, servida en un caldo aromático.",
    steps: [
      "Paso 1: Cocer los fideos de arroz.",
      "Paso 2: Preparar el caldo con especias.",
      "Paso 3: Añadir la carne de res y las hierbas frescas.",
      "Paso 4: Servir caliente.",
    ],
  },
  {
    id: "14",
    name: "Coq au Vin",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-14.webp"),
    rating: "4.8",
    ingredients: [
      "Pollo",
      "Vino Tinto",
      "Champiñones",
      "Zanahorias",
      "Cebolla",
    ],
    time: "90",
    difficulty: "Hard",
    calories: "650",
    color: "bg-purple-200",
    descrption:
      "El Coq au Vin es un plato francés clásico que consiste en pollo cocinado a fuego lento en vino tinto con champiñones, zanahorias y cebolla.",
    steps: [
      "Paso 1: Dorar el pollo en una sartén.",
      "Paso 2: Añadir vino tinto, champiñones, zanahorias y cebolla.",
      "Paso 3: Cocinar a fuego lento hasta que el pollo esté tierno.",
      "Paso 4: Servir caliente.",
    ],
  },
  {
    id: "15",
    name: "Moussaka",
    category: "Snack",
    Image: require("../../assets/imgs/snacks/receta-15.webp"),
    rating: "4.6",
    ingredients: [
      "Berenjena",
      "Carne de Cordero",
      "Tomate",
      "Queso",
      "Bechamel",
    ],
    time: "75",
    difficulty: "Medio",
    calories: "600",
    color: "bg-brown-200",
    descrption:
      "La Moussaka es un plato tradicional griego que consiste en capas de berenjena, carne de cordero, tomate y bechamel, gratinadas con queso.",
    steps: [
      "Paso 1: Freír las rodajas de berenjena.",
      "Paso 2: Cocinar la carne de cordero con tomate.",
      "Paso 3: Preparar la bechamel.",
      "Paso 4: Montar las capas y gratinar con queso.",
    ],
  },
];
